spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
#      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.OracleDialect
#      hibernate:
#        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
#        current_session_context_class: thread
#        jdbc:
#          time_zone: UTC
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@1.1.1.1:1521:aa
    username: 11
    password: 11