#http://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html
#http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
application:
  version: 1.0
  title: Board Application

spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
#    templateLoaderPath:
  config:
    location:
  application:
    name: springboot
  main:
    banner-mode: off
  h2:
    console:
      enabled: true # Enable the console.
      path: /h2-console # Path at which the console will be available.
      settings:
        trace: false # Enable trace output.
        web-allow-others: false # Enable remote access.
  datasource:
    name: testdb
    initialize: true  # Populate the database using 'data.sql'.
    #schema:
    #data:
    platform: all # Platform to use in the schema resource (schema-${platform}.sql).
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    continue-on-error: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    show-sql: true
#    open-in-view: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate.current_session_context_class: thread
#      hibernate.jdbc.batch_size: 50
#      hibernate.format_sql: false
#      hibernate.validator.apply_to_ddl: false
#      hibernate.validator.autoregister_listeners: false
#      javax.persistence.validation.mode: none
##      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  data:
    repositories:
      enabled: true
  http:
    multipart:
      enabled: true # Enable support of multi-part uploads.
  mvc:
    locale: ko_KR
  groovy:
    template:
      cache: false
  # INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
#    always-use-message-format: false # Set whether to always apply the MessageFormat rules, parsing even messages without arguments.
    cache-seconds: -1 # Loaded resource bundle files cache expiration, in seconds. When set to -1, bundles are cached forever.
    basename: classpath:/messages/message # Comma-separated list of basenames, each following the ResourceBundle convention.
    encoding: UTF-8 # Message bundles encoding.
#    fallback-to-system-locale: true # Set whether to fall back to the system Locale if no files for a specific Locale have been found.



# SECURITY (SecurityProperties)
security:
  basic:
    authorize-mode: role # Security authorize mode to apply.
    enabled: true # Enable basic authentication.
    path: /** # Comma-separated list of paths to secure.
    realm: Spring # HTTP basic realm name.
  enable-csrf: true # Enable Cross Site Request Forgery support.
  filter-order: 0 # Security filter chain order.
  filter-dispatcher-types: ASYNC, FORWARD, INCLUDE, REQUEST # Security filter chain dispatcher types.
  headers:
    cache: true # Enable cache control HTTP headers.
    content-type: true # Enable "X-Content-Type-Options" header.
    frame: true # Enable "X-Frame-Options" header.
    #hsts= # HTTP Strict Transport Security (HSTS) mode (none, domain, all).
    xss: true # Enable cross site scripting (XSS) protection.
  #ignored= # Comma-separated list of paths to exclude from the default secured paths.
  require-ssl: false # Enable secure channel for all requests.
  sessions: stateless # Session creation policy (always, never, if_required, stateless).
  user:
    name: user # Default admin name.
    password: user # Password for the default admin name. A random password is logged on startup by default.
    role: USER # Granted roles for the default admin name.
#  oauth2:
#    resource:
#      user-info-uri: /api
#    client:
#      client-id: user
#      client-secret: user
#      access-token-validity-seconds: 1800
#      refresh-token-validity-seconds: 1800
#  view:
#      prefix:
#      suffix: :.vm

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.khh: INFO

multipart:
  maxFileSize: 10Mb


######## CUSTOM PROPERTIES ##########
hibernate:
  mapping-locations: classpath:hibernate/*.hbm.xml
#  packages-to-scan: com.khh.project
#  annotated-packages: com.khh.project
  properties:
#    hibernate.connection.url
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.hbm2ddl.auto: update
    hibernate.current_session_context_class: thread

project:
  locale-change:
    param-name: lang
  properties:
    hello: hello22






---

spring:
  profiles: development

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.khh: DEBUG

---

spring:
  profiles: production

logging:
  #file: logs/application.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.khh: INFO


