#http://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html
#http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
application:
  version: 1.0
  title: API-CMS Application
server:
  port: 8180
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.current_session_context_class: thread
      hibernate.jdbc.batch_size: 50
      hibernate.format_sql: false
      hibernate.validator.apply_to_ddl: false
      hibernate.validator.autoregister_listeners: false
      javax.persistence.validation.mode: none
      hibernate.hbm2ddl.auto: none

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.nhis: DEBUG


######## CUSTOM PROPERTIES ##########
hibernate:
  mapping-locations: classpath:hibernate/*.hbm.xml
#  packages-to-scan: com.khh.project
#  annotated-packages: com.khh.project
  properties:
#    hibernate.connection.url
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.hbm2ddl.auto: none
    hibernate.current_session_context_class: thread
    hibernate.validator.apply_to_ddl: false
    hibernate.validator.autoregister_listeners: false

project:
  locale-change:
    param-name: lang
  multipart:
    maxFileSize: 10Mb
  properties:
    hello: hello22
encryp:
  http-body-key: vi4s5uaa7sdlkhh
  privacy-key: hits52a35s6lhvj


